### ISSUE TITLE
Stack analysis for NPM workspace fails due to target error

### ISSUE THREAD

**Issue by sara-02** [fabric8-analytics/fabric8-analytics-vscode-extension#151]
When I am at the package.json and run stack analysis for the whole workspace, it gets into a target not getting generated error.
For the same package.json when stack report is run for given package, I am stuck at generating stack report, but progress is logged in the developer toggle.

![screenshot from 2018-08-23 12-50-28](https://user-images.githubusercontent.com/7047079/44510848-65247b00-a6d3-11e8-89ab-ae5881fb116a.png)
![screenshot from 2018-08-23 12-56-05](https://user-images.githubusercontent.com/7047079/44511054-f267cf80-a6d3-11e8-97fd-14963d1dec78.png)

Error log:
```

e.$onExtensionRuntimeError @ /usr/share/code/resources/app/out/vs/workbench/workbench.main.js:3227

Error: ENOENT: no such file or directory, mkdir '/home/smasud/sententree/target'
	at Object.fs.mkdirSync (fs.js:885:18)
	at getDependencyVersion (/home/smasud/.vscode/extensions/redhat.fabric8-analytics-0.0.3/out/src/ProjectDataProvider.js:149:16)
	at Object.ProjectDataProvider.effectivef8Package (/home/smasud/.vscode/extensions/redhat.fabric8-analytics-0.0.3/out/src/ProjectDataProvider.js:71:9)
	at vscode.workspace.findFiles.then (/home/smasud/.vscode/extensions/redhat.fabric8-analytics-0.0.3/out/src/extension.js:130:75)
	at Object.g [as _notify] (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:77:971)
	at Object.enter (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:81:277)
	at n.Class.derive._oncancel._run (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:83:100)
	at n.Class.derive._oncancel._completed (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:82:559)
	at e.resolveOk (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:573:721)
	at e._receiveReply (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:671:316)
	at e._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:670:609)
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:669:452
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:672:575
	at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:96:903
	at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:98:218)
	at a (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:162:713)
	at Socket._socketDataListener (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:162:932)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at addChunk (_stream_readable.js:263:12)
	at readableAddChunk (_stream_readable.js:250:11)
	at Socket.Readable.push (_stream_readable.js:208:10)
	at Pipe.onread (net.js:594:20)
```
VSCode: 1.26.1
Os: Fedora
Package: sententree
Github: https://github.com/twitter/SentenTree

**Comment by sara-02** [comment]
This is an error due to camel casing of the project name when I manually changed the project name to lowercase it worked as expected.
![screenshot from 2018-08-23 13-56-31](https://user-images.githubusercontent.com/7047079/44513923-59898200-a6dc-11e8-8a68-b54194e85b08.png)

**Comment by sara-02** [comment]
Also, it does not stop after the error, the `generating stack report` message continues, even though an error has been detected.
