### ISSUE TITLE
[BUG] Cannot read property '1' of null

### ISSUE THREAD

**Issue by Fydon** [fabric8-analytics/fabric8-analytics-vscode-extension#481]
**Describe the bug**
Extension crashes on start of VSCode since 0.3.0. Reverting to 0.2.1 causes it to work again.

```
TypeError: Cannot read property '1' of null
    at Ct (c:\Users\username\.vscode-insiders\extensions\redhat.fabric8-analytics-0.3.0\dist\server.js:9:149473)
    at Object.e.initRecognizerEngine (c:\Users\username\.vscode-insiders\extensions\redhat.fabric8-analytics-0.3.0\dist\server.js:9:163475)
    at Object.e (c:\Users\username\.vscode-insiders\extensions\redhat.fabric8-analytics-0.3.0\dist\server.js:9:181832)
    at new t (c:\Users\username\.vscode-insiders\extensions\redhat.fabric8-analytics-0.3.0\dist\server.js:9:184347)
    at new <anonymous> (c:\Users\username\.vscode-insiders\extensions\redhat.fabric8-analytics-0.3.0\dist\server.js:9:543516)
    at Object.<anonymous> (c:\Users\username\.vscode-insiders\extensions\redhat.fabric8-analytics-0.3.0\dist\server.js:9:543482)
    at n (c:\Users\username\.vscode-insiders\extensions\redhat.fabric8-analytics-0.3.0\dist\server.js:1:124)
    at Object.<anonymous> (c:\Users\username\.vscode-insiders\extensions\redhat.fabric8-analytics-0.3.0\dist\server.js:9:299607)
    at n (c:\Users\username\.vscode-insiders\extensions\redhat.fabric8-analytics-0.3.0\dist\server.js:1:124)
    at Object.<anonymous> (c:\Users\username\.vscode-insiders\extensions\redhat.fabric8-analytics-0.3.0\dist\server.js:9:541338)
[Error - 05:51:12] Connection to server got closed. Server will not be restarted.
```

```
Version: 1.53.0-insider (system setup)
Commit: eaa959d34b863dec932077d94daece22504a396b
Date: 2021-01-18T05:13:25.733Z
Electron: 11.2.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```

**To Reproduce**
1. Open VSCode.

**Expected behavior**
Doesn't crash

**VSCode(please complete the following information):**
 - OS: Windows 10
 - VSCode version 1.53.0-inside
 - Dependency Analytics Version 0.3.0

**Comment by arajkumar** [comment]
@Fydon Thanks for reporting this. Can you test with the latest stable?

**Comment by arajkumar** [comment]
It works on latest stable vscode which has node 12.14.1., however fails on insider which has 12.18.3. It is a bug, which need to fixed.

**Comment by arajkumar** [comment]
After an extensive analysis, we found that the `chevrotain@7.0.1` which is used by `@xml-tools/parser` is [causing the trouble](https://github.com/SAP/chevrotain/pull/1269). We also tried to upgrade chevrotain independently, but npm doesn't really allow it due to version pinning from `@xml-tools/parser`[ package.json](https://github.com/SAP/xml-tools/blob/master/packages/parser/package.json#L19).

### Possible Solutions

- Switch to yarn, it allows [selective transitive dependency](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) version upgrade
- Disable webpack minimisation
- Get it fixed from `@xml-tools/parser` - https://github.com/SAP/xml-tools/pull/282

**Comment by arajkumar** [comment]
@Fydon , can you please check with our latest release 0.3.1? It should fix the problem.

Thanks for reporting this issue.

**Comment by Fydon** [comment]
@arajkumar Thank you for the speed in fixing this. Yes it seems to be working now.

**Comment by arajkumar** [comment]
> @arajkumar Thank you for the speed in fixing this. Yes it seems to be working now.

@Fydon You are welcome :) Hope our extension provides value add to your development cycle.
